### ISSUE TITLE
Use prepared statements in SQL for PID get/put

### ISSUE THREAD

**Issue by jmandel** [RSNA/s4s-fhir-broker#1]
[This code](https://github.com/RSNA/s4s-fhir-broker/blob/42872dea8d218fa18ec58b54171b9980b2925c97/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/PidLookup.java#L41-L92) for looking up FHIR IDs winds up directly executing statements that include non-sanitized inputs -- this can lead to SQL injection. For example:

    s = "INSERT INTO pid_lookup VALUES ('" + pidIn + "', '" + pidOut + "')";

Can this be updated to use prepared statements?

**Comment by rmoult01** [comment]
updated to use prepared statements. TOK
