### ISSUE TITLE
It it possible to avoid 71 MB WAR file in repository?

### ISSUE THREAD

**Issue by jmandel** [RSNA/s4s-fhir-broker#2]
It looks like `s4s-fhir-broker/hapi-fhir-jpaserver-example/target/hapi-fhir-jpaserver-example.war` is a 71MB .war file directly in the repository. Can we think about strategies for building this artifact when/where needed (e.g. as part of a docker build) rather than checking the result into version control? I'm concerned about the impact on developer workflow, especial when/if this file changes.

**Comment by kelseym** [comment]
I've added a maven build step as an image layer in the fhir-broker Dockerfile. The .war file is now generated as part of the docker build and has been removed from the git repo.
